name: Changeset

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!README.md"
      - "!docs/**"

concurrency:
  group: changeset-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changeset:
    if: >-
      ${{ github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'chore(release): version packages') }}
    name: Changeset
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run version-packages
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
